# MIT License
# 
# Copyright (c) 2022 Can Aknesil
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

create_pblock pblock_1
add_cells_to_pblock [get_pblocks pblock_1] [get_cells -quiet [list antenna_top/LOOPP]]
resize_pblock [get_pblocks pblock_1] -add {SLICE_X0Y0:SLICE_X5Y7}
set_property BEL A6LUT [get_cells antenna_top/LOOPP/lines1_inst]
set_property BEL A5LUT [get_cells antenna_top/LOOPP/lines1_inst__3]
set_property BEL A6LUT [get_cells antenna_top/LOOPP/lines1_inst__22]
set_property BEL A6LUT [get_cells antenna_top/LOOPP/lines1_inst__5]
set_property BEL A5LUT [get_cells antenna_top/LOOPP/lines1_inst__6]
set_property BEL A6LUT [get_cells antenna_top/LOOPP/lines1_inst__19]
set_property BEL A6LUT [get_cells antenna_top/LOOPP/stem_end_inferred_i_3]
set_property BEL B6LUT [get_cells antenna_top/LOOPP/stem_end_inferred_i_4]
set_property BEL A6LUT [get_cells antenna_top/LOOPP/lines1_inst__11]
set_property BEL A6LUT [get_cells antenna_top/LOOPP/lines1_inst__13]
set_property BEL A5LUT [get_cells antenna_top/LOOPP/lines1_inst__21]
set_property BEL A6LUT [get_cells antenna_top/LOOPP/stem_end_inferred_i_2]
set_property BEL A5LUT [get_cells antenna_top/LOOPP/lines1_inst__0]
set_property BEL A5LUT [get_cells antenna_top/LOOPP/lines1_inst__14]
set_property BEL B6LUT [get_cells antenna_top/LOOPP/stem_end_inferred_i_1]
set_property BEL D6LUT [get_cells antenna_top/LOOPP/stem_start_inst]
set_property BEL A5LUT [get_cells antenna_top/LOOPP/lines1_inst__2]
set_property BEL A6LUT [get_cells antenna_top/LOOPP/lines1_inst__20]
set_property BEL A5LUT [get_cells antenna_top/LOOPP/lines1_inst__1]
set_property BEL A6LUT [get_cells antenna_top/LOOPP/lines1_inst__17]
set_property BEL B6LUT [get_cells antenna_top/LOOPP/lines1_inst__7]
set_property BEL A6LUT [get_cells antenna_top/LOOPP/lines1_inst__4]
set_property BEL A5LUT [get_cells antenna_top/LOOPP/lines1_inst__12]
set_property BEL A6LUT [get_cells antenna_top/LOOPP/lines1_inst__15]
set_property BEL A5LUT [get_cells antenna_top/LOOPP/lines1_inst__16]
set_property BEL A6LUT [get_cells antenna_top/LOOPP/lines1_inst__10]
set_property BEL A5LUT [get_cells antenna_top/LOOPP/lines1_inst__18]
set_property BEL A5LUT [get_cells antenna_top/LOOPP/lines1_inst__8]
set_property BEL A6LUT [get_cells antenna_top/LOOPP/lines1_inst__9]
set_property BEL B6LUT [get_cells antenna_top/LOOPP/stem_end_inferred_i_5]
set_property LOC SLICE_X3Y6 [get_cells antenna_top/LOOPP/lines1_inst]
set_property LOC SLICE_X4Y4 [get_cells antenna_top/LOOPP/lines1_inst__3]
set_property LOC SLICE_X4Y4 [get_cells antenna_top/LOOPP/lines1_inst__22]
set_property LOC SLICE_X3Y5 [get_cells antenna_top/LOOPP/lines1_inst__5]
set_property LOC SLICE_X3Y5 [get_cells antenna_top/LOOPP/lines1_inst__6]
set_property LOC SLICE_X2Y2 [get_cells antenna_top/LOOPP/lines1_inst__19]
set_property LOC SLICE_X3Y2 [get_cells antenna_top/LOOPP/stem_end_inferred_i_3]
set_property LOC SLICE_X2Y5 [get_cells antenna_top/LOOPP/stem_end_inferred_i_4]
set_property LOC SLICE_X2Y1 [get_cells antenna_top/LOOPP/lines1_inst__11]
set_property LOC SLICE_X0Y3 [get_cells antenna_top/LOOPP/lines1_inst__13]
set_property LOC SLICE_X4Y3 [get_cells antenna_top/LOOPP/lines1_inst__21]
set_property LOC SLICE_X6Y4 [get_cells antenna_top/LOOPP/stem_end_inferred_i_2]
set_property LOC SLICE_X4Y6 [get_cells antenna_top/LOOPP/lines1_inst__0]
set_property LOC SLICE_X0Y3 [get_cells antenna_top/LOOPP/lines1_inst__14]
set_property LOC SLICE_X2Y3 [get_cells antenna_top/LOOPP/stem_end_inferred_i_1]
set_property LOC SLICE_X4Y6 [get_cells antenna_top/LOOPP/stem_start_inst]
set_property LOC SLICE_X2Y2 [get_cells antenna_top/LOOPP/lines1_inst__2]
set_property LOC SLICE_X4Y3 [get_cells antenna_top/LOOPP/lines1_inst__20]
set_property LOC SLICE_X2Y5 [get_cells antenna_top/LOOPP/lines1_inst__1]
set_property LOC SLICE_X6Y2 [get_cells antenna_top/LOOPP/lines1_inst__17]
set_property LOC SLICE_X2Y6 [get_cells antenna_top/LOOPP/lines1_inst__7]
set_property LOC SLICE_X2Y3 [get_cells antenna_top/LOOPP/lines1_inst__4]
set_property LOC SLICE_X2Y1 [get_cells antenna_top/LOOPP/lines1_inst__12]
set_property LOC SLICE_X0Y5 [get_cells antenna_top/LOOPP/lines1_inst__15]
set_property LOC SLICE_X0Y5 [get_cells antenna_top/LOOPP/lines1_inst__16]
set_property LOC SLICE_X2Y5 [get_cells antenna_top/LOOPP/lines1_inst__10]
set_property LOC SLICE_X6Y2 [get_cells antenna_top/LOOPP/lines1_inst__18]
set_property LOC SLICE_X3Y6 [get_cells antenna_top/LOOPP/lines1_inst__8]
set_property LOC SLICE_X4Y6 [get_cells antenna_top/LOOPP/lines1_inst__9]
set_property LOC SLICE_X0Y3 [get_cells antenna_top/LOOPP/stem_end_inferred_i_5]
set_property BEL A6LUT [get_cells antenna_top/LOOPP/lines1_inst__23]
set_property LOC SLICE_X76Y4 [get_cells antenna_top/LOOPP/lines1_inst__23]
set_property BEL B6LUT [get_cells antenna_top/LOOPP/lines1_inst__24]
set_property LOC SLICE_X76Y4 [get_cells antenna_top/LOOPP/lines1_inst__24]
set_property BEL A6LUT [get_cells antenna_top/LOOPP/lines1_inst__25]
set_property LOC SLICE_X77Y4 [get_cells antenna_top/LOOPP/lines1_inst__25]
set_property BEL B6LUT [get_cells antenna_top/LOOPP/lines1_inst__26]
set_property LOC SLICE_X77Y6 [get_cells antenna_top/LOOPP/lines1_inst__26]
set_property BEL A6LUT [get_cells antenna_top/LOOPP/lines1_inst__27]
set_property LOC SLICE_X79Y8 [get_cells antenna_top/LOOPP/lines1_inst__27]
set_property BEL A6LUT [get_cells antenna_top/LOOPP/lines1_inst__28]
set_property LOC SLICE_X77Y7 [get_cells antenna_top/LOOPP/lines1_inst__28]
set_property BEL B6LUT [get_cells antenna_top/LOOPP/lines1_inst__29]
set_property LOC SLICE_X77Y9 [get_cells antenna_top/LOOPP/lines1_inst__29]
set_property BEL C6LUT [get_cells antenna_top/LOOPP/lines1_inst__30]
set_property LOC SLICE_X77Y9 [get_cells antenna_top/LOOPP/lines1_inst__30]
set_property BEL A6LUT [get_cells antenna_top/LOOPP/lines1_inst__31]
set_property LOC SLICE_X76Y10 [get_cells antenna_top/LOOPP/lines1_inst__31]
set_property BEL B6LUT [get_cells antenna_top/LOOPP/lines1_inst__32]
set_property LOC SLICE_X77Y10 [get_cells antenna_top/LOOPP/lines1_inst__32]
set_property BEL A6LUT [get_cells antenna_top/LOOPP/lines1_inst__33]
set_property LOC SLICE_X79Y10 [get_cells antenna_top/LOOPP/lines1_inst__33]
set_property BEL C6LUT [get_cells antenna_top/LOOPP/lines1_inst__34]
set_property LOC SLICE_X76Y9 [get_cells antenna_top/LOOPP/lines1_inst__34]
set_property BEL C6LUT [get_cells antenna_top/LOOPP/lines1_inst__35]
set_property LOC SLICE_X76Y4 [get_cells antenna_top/LOOPP/lines1_inst__35]
set_property BEL B6LUT [get_cells antenna_top/LOOPP/lines1_inst__36]
set_property LOC SLICE_X77Y4 [get_cells antenna_top/LOOPP/lines1_inst__36]
set_property BEL D6LUT [get_cells antenna_top/LOOPP/lines1_inst__37]
set_property LOC SLICE_X74Y4 [get_cells antenna_top/LOOPP/lines1_inst__37]
set_property BEL A6LUT [get_cells antenna_top/LOOPP/lines1_inst__38]
set_property LOC SLICE_X75Y7 [get_cells antenna_top/LOOPP/lines1_inst__38]
set_property BEL A6LUT [get_cells antenna_top/LOOPP/lines1_inst__39]
set_property LOC SLICE_X75Y9 [get_cells antenna_top/LOOPP/lines1_inst__39]
set_property BEL B6LUT [get_cells antenna_top/LOOPP/lines1_inst__40]
set_property LOC SLICE_X75Y9 [get_cells antenna_top/LOOPP/lines1_inst__40]
set_property BEL A6LUT [get_cells antenna_top/LOOPP/lines1_inst__41]
set_property LOC SLICE_X81Y6 [get_cells antenna_top/LOOPP/lines1_inst__41]
set_property BEL B6LUT [get_cells antenna_top/LOOPP/lines1_inst__42]
set_property LOC SLICE_X81Y6 [get_cells antenna_top/LOOPP/lines1_inst__42]
set_property BEL B6LUT [get_cells antenna_top/LOOPP/lines1_inst__43]
set_property LOC SLICE_X76Y6 [get_cells antenna_top/LOOPP/lines1_inst__43]
set_property BEL A6LUT [get_cells antenna_top/LOOPP/lines1_inst__44]
set_property LOC SLICE_X78Y7 [get_cells antenna_top/LOOPP/lines1_inst__44]
set_property BEL B6LUT [get_cells antenna_top/LOOPP/lines1_inst__45]
set_property LOC SLICE_X78Y7 [get_cells antenna_top/LOOPP/lines1_inst__45]
set_property BEL B6LUT [get_cells antenna_top/LOOPP/lines1_inst__46]
set_property LOC SLICE_X79Y8 [get_cells antenna_top/LOOPP/lines1_inst__46]
set_property BEL A5LUT [get_cells antenna_top/LOOPP/lines1_inst__47]
set_property LOC SLICE_X76Y7 [get_cells antenna_top/LOOPP/lines1_inst__47]
set_property BEL D6LUT [get_cells antenna_top/LOOPP/lines2_inst]
set_property LOC SLICE_X76Y191 [get_cells antenna_top/LOOPP/lines2_inst]
set_property BEL A5LUT [get_cells antenna_top/LOOPP/lines2_inst__0]
set_property LOC SLICE_X76Y191 [get_cells antenna_top/LOOPP/lines2_inst__0]
set_property BEL C6LUT [get_cells antenna_top/LOOPP/lines2_inst__1]
set_property LOC SLICE_X77Y191 [get_cells antenna_top/LOOPP/lines2_inst__1]
set_property BEL C6LUT [get_cells antenna_top/LOOPP/lines2_inst__2]
set_property LOC SLICE_X76Y193 [get_cells antenna_top/LOOPP/lines2_inst__2]
set_property BEL A6LUT [get_cells antenna_top/LOOPP/lines2_inst__3]
set_property LOC SLICE_X78Y195 [get_cells antenna_top/LOOPP/lines2_inst__3]
set_property BEL C6LUT [get_cells antenna_top/LOOPP/lines2_inst__4]
set_property LOC SLICE_X76Y194 [get_cells antenna_top/LOOPP/lines2_inst__4]
set_property BEL D6LUT [get_cells antenna_top/LOOPP/lines2_inst__5]
set_property LOC SLICE_X77Y196 [get_cells antenna_top/LOOPP/lines2_inst__5]
set_property BEL B5LUT [get_cells antenna_top/LOOPP/lines2_inst__6]
set_property LOC SLICE_X77Y196 [get_cells antenna_top/LOOPP/lines2_inst__6]
set_property BEL C6LUT [get_cells antenna_top/LOOPP/lines2_inst__7]
set_property LOC SLICE_X76Y197 [get_cells antenna_top/LOOPP/lines2_inst__7]
set_property BEL C6LUT [get_cells antenna_top/LOOPP/lines2_inst__8]
set_property LOC SLICE_X77Y197 [get_cells antenna_top/LOOPP/lines2_inst__8]
set_property BEL A6LUT [get_cells antenna_top/LOOPP/lines2_inst__9]
set_property LOC SLICE_X78Y197 [get_cells antenna_top/LOOPP/lines2_inst__9]
set_property BEL D6LUT [get_cells antenna_top/LOOPP/lines2_inst__10]
set_property LOC SLICE_X76Y196 [get_cells antenna_top/LOOPP/lines2_inst__10]
set_property BEL B5LUT [get_cells antenna_top/LOOPP/lines2_inst__11]
set_property LOC SLICE_X76Y191 [get_cells antenna_top/LOOPP/lines2_inst__11]
set_property BEL D6LUT [get_cells antenna_top/LOOPP/lines2_inst__12]
set_property LOC SLICE_X77Y191 [get_cells antenna_top/LOOPP/lines2_inst__12]
set_property BEL A6LUT [get_cells antenna_top/LOOPP/lines2_inst__13]
set_property LOC SLICE_X74Y191 [get_cells antenna_top/LOOPP/lines2_inst__13]
set_property BEL B6LUT [get_cells antenna_top/LOOPP/lines2_inst__14]
set_property LOC SLICE_X75Y194 [get_cells antenna_top/LOOPP/lines2_inst__14]
set_property BEL A6LUT [get_cells antenna_top/LOOPP/lines2_inst__15]
set_property LOC SLICE_X74Y196 [get_cells antenna_top/LOOPP/lines2_inst__15]
set_property BEL B6LUT [get_cells antenna_top/LOOPP/lines2_inst__16]
set_property LOC SLICE_X74Y196 [get_cells antenna_top/LOOPP/lines2_inst__16]
set_property BEL B6LUT [get_cells antenna_top/LOOPP/lines2_inst__17]
set_property LOC SLICE_X80Y193 [get_cells antenna_top/LOOPP/lines2_inst__17]
set_property BEL A6LUT [get_cells antenna_top/LOOPP/lines2_inst__18]
set_property LOC SLICE_X81Y195 [get_cells antenna_top/LOOPP/lines2_inst__18]
set_property BEL C6LUT [get_cells antenna_top/LOOPP/lines2_inst__19]
set_property LOC SLICE_X80Y193 [get_cells antenna_top/LOOPP/lines2_inst__19]
set_property BEL B6LUT [get_cells antenna_top/LOOPP/lines2_inst__20]
set_property LOC SLICE_X81Y195 [get_cells antenna_top/LOOPP/lines2_inst__20]
set_property BEL A6LUT [get_cells antenna_top/LOOPP/lines2_inst__21]
set_property LOC SLICE_X78Y194 [get_cells antenna_top/LOOPP/lines2_inst__21]
set_property BEL C6LUT [get_cells antenna_top/LOOPP/lines2_inst__22]
set_property LOC SLICE_X79Y195 [get_cells antenna_top/LOOPP/lines2_inst__22]
set_property BEL B6LUT [get_cells antenna_top/LOOPP/lines2_inst__23]
set_property LOC SLICE_X77Y194 [get_cells antenna_top/LOOPP/lines2_inst__23]
set_property BEL C5LUT [get_cells antenna_top/LOOPP/lines3_inst]
set_property LOC SLICE_X2Y189 [get_cells antenna_top/LOOPP/lines3_inst]
set_property BEL A5LUT [get_cells antenna_top/LOOPP/lines3_inst__0]
set_property LOC SLICE_X3Y189 [get_cells antenna_top/LOOPP/lines3_inst__0]
set_property BEL B5LUT [get_cells antenna_top/LOOPP/lines3_inst__1]
set_property LOC SLICE_X3Y189 [get_cells antenna_top/LOOPP/lines3_inst__1]
set_property BEL D6LUT [get_cells antenna_top/LOOPP/lines3_inst__2]
set_property LOC SLICE_X2Y191 [get_cells antenna_top/LOOPP/lines3_inst__2]
set_property BEL D6LUT [get_cells antenna_top/LOOPP/lines3_inst__3]
set_property LOC SLICE_X4Y193 [get_cells antenna_top/LOOPP/lines3_inst__3]
set_property BEL C6LUT [get_cells antenna_top/LOOPP/lines3_inst__4]
set_property LOC SLICE_X3Y192 [get_cells antenna_top/LOOPP/lines3_inst__4]
set_property BEL C5LUT [get_cells antenna_top/LOOPP/lines3_inst__5]
set_property LOC SLICE_X3Y194 [get_cells antenna_top/LOOPP/lines3_inst__5]
set_property BEL D5LUT [get_cells antenna_top/LOOPP/lines3_inst__6]
set_property LOC SLICE_X2Y194 [get_cells antenna_top/LOOPP/lines3_inst__6]
set_property BEL D6LUT [get_cells antenna_top/LOOPP/lines3_inst__7]
set_property LOC SLICE_X2Y195 [get_cells antenna_top/LOOPP/lines3_inst__7]
set_property BEL D6LUT [get_cells antenna_top/LOOPP/lines3_inst__8]
set_property LOC SLICE_X3Y195 [get_cells antenna_top/LOOPP/lines3_inst__8]
set_property BEL C6LUT [get_cells antenna_top/LOOPP/lines3_inst__9]
set_property LOC SLICE_X4Y195 [get_cells antenna_top/LOOPP/lines3_inst__9]
set_property BEL C5LUT [get_cells antenna_top/LOOPP/lines3_inst__10]
set_property LOC SLICE_X2Y194 [get_cells antenna_top/LOOPP/lines3_inst__10]
set_property BEL D5LUT [get_cells antenna_top/LOOPP/lines3_inst__11]
set_property LOC SLICE_X2Y189 [get_cells antenna_top/LOOPP/lines3_inst__11]
set_property BEL C5LUT [get_cells antenna_top/LOOPP/lines3_inst__12]
set_property LOC SLICE_X3Y189 [get_cells antenna_top/LOOPP/lines3_inst__12]
set_property BEL C6LUT [get_cells antenna_top/LOOPP/lines3_inst__13]
set_property LOC SLICE_X0Y189 [get_cells antenna_top/LOOPP/lines3_inst__13]
set_property BEL C6LUT [get_cells antenna_top/LOOPP/lines3_inst__14]
set_property LOC SLICE_X0Y192 [get_cells antenna_top/LOOPP/lines3_inst__14]
set_property BEL D6LUT [get_cells antenna_top/LOOPP/lines3_inst__15]
set_property LOC SLICE_X0Y192 [get_cells antenna_top/LOOPP/lines3_inst__15]
set_property BEL D6LUT [get_cells antenna_top/LOOPP/lines3_inst__16]
set_property LOC SLICE_X0Y194 [get_cells antenna_top/LOOPP/lines3_inst__16]
set_property BEL C6LUT [get_cells antenna_top/LOOPP/lines3_inst__17]
set_property LOC SLICE_X7Y193 [get_cells antenna_top/LOOPP/lines3_inst__17]
set_property BEL B6LUT [get_cells antenna_top/LOOPP/lines3_inst__18]
set_property LOC SLICE_X6Y193 [get_cells antenna_top/LOOPP/lines3_inst__18]
set_property BEL D6LUT [get_cells antenna_top/LOOPP/lines3_inst__19]
set_property LOC SLICE_X6Y191 [get_cells antenna_top/LOOPP/lines3_inst__19]
set_property BEL C6LUT [get_cells antenna_top/LOOPP/lines3_inst__20]
set_property LOC SLICE_X6Y193 [get_cells antenna_top/LOOPP/lines3_inst__20]
set_property BEL D6LUT [get_cells antenna_top/LOOPP/lines3_inst__21]
set_property LOC SLICE_X6Y193 [get_cells antenna_top/LOOPP/lines3_inst__21]
set_property BEL C6LUT [get_cells antenna_top/LOOPP/lines3_inst__22]
set_property LOC SLICE_X4Y193 [get_cells antenna_top/LOOPP/lines3_inst__22]
set_property BEL D6LUT [get_cells antenna_top/LOOPP/lines3_inst__23]
set_property LOC SLICE_X2Y192 [get_cells antenna_top/LOOPP/lines3_inst__23]
