# MIT License
# 
# Copyright (c) 2022 Can Aknesil
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


# 100 lines

create_pblock pblock_1
add_cells_to_pblock [get_pblocks pblock_1] [get_cells -quiet [list antenna_top/MONOPOLE]]
resize_pblock [get_pblocks pblock_1] -add {SLICE_X44Y3:SLICE_X47Y7}
set_property BEL B6LUT [get_cells antenna_top/MONOPOLE/lines_inst__20]
set_property BEL C5LUT [get_cells antenna_top/MONOPOLE/lines_inst__6]
set_property BEL B6LUT [get_cells antenna_top/MONOPOLE/lines_inst__85]
set_property BEL A6LUT [get_cells antenna_top/MONOPOLE/lines_inst__89]
set_property BEL C6LUT [get_cells antenna_top/MONOPOLE/lines_inst__93]
set_property BEL C5LUT [get_cells antenna_top/MONOPOLE/lines_inst__7]
set_property BEL C6LUT [get_cells antenna_top/MONOPOLE/lines_inst__70]
set_property BEL A6LUT [get_cells antenna_top/MONOPOLE/lines_inst__10]
set_property BEL C6LUT [get_cells antenna_top/MONOPOLE/lines_inst__81]
set_property BEL B5LUT [get_cells antenna_top/MONOPOLE/lines_inst__14]
set_property BEL A6LUT [get_cells antenna_top/MONOPOLE/lines_inst__17]
set_property BEL A5LUT [get_cells antenna_top/MONOPOLE/lines_inst__23]
set_property BEL A6LUT [get_cells antenna_top/MONOPOLE/lines_inst__83]
set_property BEL D6LUT [get_cells antenna_top/MONOPOLE/stem_end_inferred_i_8]
set_property BEL D6LUT [get_cells antenna_top/MONOPOLE/stem_start_inst]
set_property BEL D6LUT [get_cells antenna_top/MONOPOLE/stem_end_inferred_i_10]
set_property BEL B6LUT [get_cells antenna_top/MONOPOLE/lines_inst__79]
set_property BEL B6LUT [get_cells antenna_top/MONOPOLE/lines_inst__31]
set_property BEL C6LUT [get_cells antenna_top/MONOPOLE/lines_inst__97]
set_property BEL B5LUT [get_cells antenna_top/MONOPOLE/lines_inst__92]
set_property BEL B6LUT [get_cells antenna_top/MONOPOLE/lines_inst__73]
set_property BEL A6LUT [get_cells antenna_top/MONOPOLE/lines_inst__77]
set_property BEL A5LUT [get_cells antenna_top/MONOPOLE/lines_inst__47]
set_property BEL A6LUT [get_cells antenna_top/MONOPOLE/lines_inst__30]
set_property BEL B5LUT [get_cells antenna_top/MONOPOLE/lines_inst__27]
set_property BEL B6LUT [get_cells antenna_top/MONOPOLE/lines_inst__62]
set_property BEL C6LUT [get_cells antenna_top/MONOPOLE/lines_inst__64]
set_property BEL B6LUT [get_cells antenna_top/MONOPOLE/lines_inst__50]
set_property BEL A6LUT [get_cells antenna_top/MONOPOLE/lines_inst__66]
set_property BEL B5LUT [get_cells antenna_top/MONOPOLE/lines_inst__4]
set_property BEL C5LUT [get_cells antenna_top/MONOPOLE/lines_inst__45]
set_property BEL A5LUT [get_cells antenna_top/MONOPOLE/lines_inst__54]
set_property BEL C5LUT [get_cells antenna_top/MONOPOLE/lines_inst__34]
set_property BEL B6LUT [get_cells antenna_top/MONOPOLE/lines_inst__68]
set_property BEL A6LUT [get_cells antenna_top/MONOPOLE/lines_inst__46]
set_property BEL B6LUT [get_cells antenna_top/MONOPOLE/lines_inst__42]
set_property BEL B6LUT [get_cells antenna_top/MONOPOLE/lines_inst__55]
set_property BEL A6LUT [get_cells antenna_top/MONOPOLE/lines_inst__53]
set_property BEL C5LUT [get_cells antenna_top/MONOPOLE/lines_inst__65]
set_property BEL A6LUT [get_cells antenna_top/MONOPOLE/lines_inst__60]
set_property BEL B5LUT [get_cells antenna_top/MONOPOLE/lines_inst__43]
set_property BEL C6LUT [get_cells antenna_top/MONOPOLE/lines_inst__33]
set_property BEL B5LUT [get_cells antenna_top/MONOPOLE/lines_inst__49]
set_property BEL A5LUT [get_cells antenna_top/MONOPOLE/lines_inst__36]
set_property BEL A6LUT [get_cells antenna_top/MONOPOLE/lines_inst__19]
set_property BEL A5LUT [get_cells antenna_top/MONOPOLE/lines_inst__3]
set_property BEL A5LUT [get_cells antenna_top/MONOPOLE/lines_inst__18]
set_property BEL B5LUT [get_cells antenna_top/MONOPOLE/lines_inst__21]
set_property BEL A5LUT [get_cells antenna_top/MONOPOLE/lines_inst__25]
set_property BEL C6LUT [get_cells antenna_top/MONOPOLE/lines_inst__15]
set_property BEL B5LUT [get_cells antenna_top/MONOPOLE/lines_inst__86]
set_property BEL B6LUT [get_cells antenna_top/MONOPOLE/lines_inst__91]
set_property BEL A5LUT [get_cells antenna_top/MONOPOLE/lines_inst__78]
set_property BEL A5LUT [get_cells antenna_top/MONOPOLE/lines_inst__96]
set_property BEL B6LUT [get_cells antenna_top/MONOPOLE/lines_inst__13]
set_property BEL C5LUT [get_cells antenna_top/MONOPOLE/lines_inst__88]
set_property BEL A6LUT [get_cells antenna_top/MONOPOLE/lines_inst__71]
set_property BEL A5LUT [get_cells antenna_top/MONOPOLE/lines_inst__72]
set_property BEL B5LUT [get_cells antenna_top/MONOPOLE/lines_inst__74]
set_property BEL C5LUT [get_cells antenna_top/MONOPOLE/lines_inst__76]
set_property BEL A5LUT [get_cells antenna_top/MONOPOLE/lines_inst__61]
set_property BEL A6LUT [get_cells antenna_top/MONOPOLE/lines_inst__24]
set_property BEL A5LUT [get_cells antenna_top/MONOPOLE/lines_inst__12]
set_property BEL A6LUT [get_cells antenna_top/MONOPOLE/lines_inst__22]
set_property BEL A6LUT [get_cells antenna_top/MONOPOLE/lines_inst__11]
set_property BEL A5LUT [get_cells antenna_top/MONOPOLE/lines_inst__8]
set_property BEL A5LUT [get_cells antenna_top/MONOPOLE/lines_inst__67]
set_property BEL A5LUT [get_cells antenna_top/MONOPOLE/lines_inst__90]
set_property BEL B5LUT [get_cells antenna_top/MONOPOLE/lines_inst__80]
set_property BEL C6LUT [get_cells antenna_top/MONOPOLE/lines_inst__87]
set_property BEL C6LUT [get_cells antenna_top/MONOPOLE/lines_inst__57]
set_property BEL C5LUT [get_cells antenna_top/MONOPOLE/lines_inst__82]
set_property BEL B5LUT [get_cells antenna_top/MONOPOLE/lines_inst__5]
set_property BEL B6LUT [get_cells antenna_top/MONOPOLE/lines_inst__26]
set_property BEL C6LUT [get_cells antenna_top/MONOPOLE/lines_inst__51]
set_property BEL A5LUT [get_cells antenna_top/MONOPOLE/lines_inst__84]
set_property BEL C6LUT [get_cells antenna_top/MONOPOLE/stem_end_inferred_i_11]
set_property BEL B6LUT [get_cells antenna_top/MONOPOLE/lines_inst__9]
set_property BEL C5LUT [get_cells antenna_top/MONOPOLE/lines_inst__94]
set_property BEL A6LUT [get_cells antenna_top/MONOPOLE/lines_inst__95]
set_property BEL C6LUT [get_cells antenna_top/MONOPOLE/lines_inst__75]
set_property BEL B5LUT [get_cells antenna_top/MONOPOLE/lines_inst__32]
set_property BEL C6LUT [get_cells antenna_top/MONOPOLE/lines_inst__59]
set_property BEL C6LUT [get_cells antenna_top/MONOPOLE/lines_inst__28]
set_property BEL B6LUT [get_cells antenna_top/MONOPOLE/lines_inst__39]
set_property BEL C5LUT [get_cells antenna_top/MONOPOLE/lines_inst__29]
set_property BEL B6LUT [get_cells antenna_top/MONOPOLE/lines_inst__37]
set_property BEL C5LUT [get_cells antenna_top/MONOPOLE/lines_inst__58]
set_property BEL B5LUT [get_cells antenna_top/MONOPOLE/lines_inst__69]
set_property BEL A6LUT [get_cells antenna_top/MONOPOLE/lines_inst__35]
set_property BEL B5LUT [get_cells antenna_top/MONOPOLE/lines_inst__56]
set_property BEL A5LUT [get_cells antenna_top/MONOPOLE/lines_inst__41]
set_property BEL C5LUT [get_cells antenna_top/MONOPOLE/lines_inst__52]
set_property BEL B5LUT [get_cells antenna_top/MONOPOLE/lines_inst__63]
set_property BEL B5LUT [get_cells antenna_top/MONOPOLE/lines_inst__38]
set_property BEL A6LUT [get_cells antenna_top/MONOPOLE/lines_inst__40]
set_property BEL B6LUT [get_cells antenna_top/MONOPOLE/lines_inst__48]
set_property BEL C6LUT [get_cells antenna_top/MONOPOLE/lines_inst__44]
set_property BEL B5LUT [get_cells antenna_top/MONOPOLE/lines_inst__0]
set_property BEL C5LUT [get_cells antenna_top/MONOPOLE/lines_inst__16]
set_property BEL A5LUT [get_cells antenna_top/MONOPOLE/lines_inst__2]
set_property BEL A6LUT [get_cells antenna_top/MONOPOLE/lines_inst]
set_property BEL A5LUT [get_cells antenna_top/MONOPOLE/lines_inst__1]
set_property LOC SLICE_X45Y6 [get_cells antenna_top/MONOPOLE/lines_inst__20]
set_property LOC SLICE_X46Y5 [get_cells antenna_top/MONOPOLE/lines_inst__6]
set_property LOC SLICE_X48Y4 [get_cells antenna_top/MONOPOLE/lines_inst__85]
set_property LOC SLICE_X46Y4 [get_cells antenna_top/MONOPOLE/lines_inst__89]
set_property LOC SLICE_X46Y4 [get_cells antenna_top/MONOPOLE/lines_inst__93]
set_property LOC SLICE_X47Y5 [get_cells antenna_top/MONOPOLE/lines_inst__7]
set_property LOC SLICE_X47Y5 [get_cells antenna_top/MONOPOLE/lines_inst__70]
set_property LOC SLICE_X47Y5 [get_cells antenna_top/MONOPOLE/lines_inst__10]
set_property LOC SLICE_X46Y3 [get_cells antenna_top/MONOPOLE/lines_inst__81]
set_property LOC SLICE_X47Y7 [get_cells antenna_top/MONOPOLE/lines_inst__14]
set_property LOC SLICE_X45Y6 [get_cells antenna_top/MONOPOLE/lines_inst__17]
set_property LOC SLICE_X43Y6 [get_cells antenna_top/MONOPOLE/lines_inst__23]
set_property LOC SLICE_X48Y4 [get_cells antenna_top/MONOPOLE/lines_inst__83]
set_property LOC SLICE_X47Y7 [get_cells antenna_top/MONOPOLE/stem_end_inferred_i_8]
set_property LOC SLICE_X46Y7 [get_cells antenna_top/MONOPOLE/stem_start_inst]
set_property LOC SLICE_X42Y7 [get_cells antenna_top/MONOPOLE/stem_end_inferred_i_10]
set_property LOC SLICE_X46Y3 [get_cells antenna_top/MONOPOLE/lines_inst__79]
set_property LOC SLICE_X44Y6 [get_cells antenna_top/MONOPOLE/lines_inst__31]
set_property LOC SLICE_X45Y5 [get_cells antenna_top/MONOPOLE/lines_inst__97]
set_property LOC SLICE_X46Y4 [get_cells antenna_top/MONOPOLE/lines_inst__92]
set_property LOC SLICE_X48Y3 [get_cells antenna_top/MONOPOLE/lines_inst__73]
set_property LOC SLICE_X46Y3 [get_cells antenna_top/MONOPOLE/lines_inst__77]
set_property LOC SLICE_X44Y5 [get_cells antenna_top/MONOPOLE/lines_inst__47]
set_property LOC SLICE_X44Y6 [get_cells antenna_top/MONOPOLE/lines_inst__30]
set_property LOC SLICE_X42Y7 [get_cells antenna_top/MONOPOLE/lines_inst__27]
set_property LOC SLICE_X42Y4 [get_cells antenna_top/MONOPOLE/lines_inst__62]
set_property LOC SLICE_X42Y4 [get_cells antenna_top/MONOPOLE/lines_inst__64]
set_property LOC SLICE_X47Y5 [get_cells antenna_top/MONOPOLE/lines_inst__50]
set_property LOC SLICE_X43Y3 [get_cells antenna_top/MONOPOLE/lines_inst__66]
set_property LOC SLICE_X46Y6 [get_cells antenna_top/MONOPOLE/lines_inst__4]
set_property LOC SLICE_X42Y6 [get_cells antenna_top/MONOPOLE/lines_inst__45]
set_property LOC SLICE_X42Y3 [get_cells antenna_top/MONOPOLE/lines_inst__54]
set_property LOC SLICE_X44Y6 [get_cells antenna_top/MONOPOLE/lines_inst__34]
set_property LOC SLICE_X43Y3 [get_cells antenna_top/MONOPOLE/lines_inst__68]
set_property LOC SLICE_X44Y5 [get_cells antenna_top/MONOPOLE/lines_inst__46]
set_property LOC SLICE_X42Y6 [get_cells antenna_top/MONOPOLE/lines_inst__42]
set_property LOC SLICE_X42Y3 [get_cells antenna_top/MONOPOLE/lines_inst__55]
set_property LOC SLICE_X42Y3 [get_cells antenna_top/MONOPOLE/lines_inst__53]
set_property LOC SLICE_X42Y4 [get_cells antenna_top/MONOPOLE/lines_inst__65]
set_property LOC SLICE_X42Y4 [get_cells antenna_top/MONOPOLE/lines_inst__60]
set_property LOC SLICE_X42Y6 [get_cells antenna_top/MONOPOLE/lines_inst__43]
set_property LOC SLICE_X44Y6 [get_cells antenna_top/MONOPOLE/lines_inst__33]
set_property LOC SLICE_X44Y5 [get_cells antenna_top/MONOPOLE/lines_inst__49]
set_property LOC SLICE_X46Y7 [get_cells antenna_top/MONOPOLE/lines_inst__36]
set_property LOC SLICE_X46Y6 [get_cells antenna_top/MONOPOLE/lines_inst__19]
set_property LOC SLICE_X44Y6 [get_cells antenna_top/MONOPOLE/lines_inst__3]
set_property LOC SLICE_X45Y6 [get_cells antenna_top/MONOPOLE/lines_inst__18]
set_property LOC SLICE_X45Y6 [get_cells antenna_top/MONOPOLE/lines_inst__21]
set_property LOC SLICE_X42Y7 [get_cells antenna_top/MONOPOLE/lines_inst__25]
set_property LOC SLICE_X47Y7 [get_cells antenna_top/MONOPOLE/lines_inst__15]
set_property LOC SLICE_X48Y4 [get_cells antenna_top/MONOPOLE/lines_inst__86]
set_property LOC SLICE_X46Y4 [get_cells antenna_top/MONOPOLE/lines_inst__91]
set_property LOC SLICE_X46Y3 [get_cells antenna_top/MONOPOLE/lines_inst__78]
set_property LOC SLICE_X45Y5 [get_cells antenna_top/MONOPOLE/lines_inst__96]
set_property LOC SLICE_X47Y7 [get_cells antenna_top/MONOPOLE/lines_inst__13]
set_property LOC SLICE_X48Y4 [get_cells antenna_top/MONOPOLE/lines_inst__88]
set_property LOC SLICE_X48Y3 [get_cells antenna_top/MONOPOLE/lines_inst__71]
set_property LOC SLICE_X48Y3 [get_cells antenna_top/MONOPOLE/lines_inst__72]
set_property LOC SLICE_X48Y3 [get_cells antenna_top/MONOPOLE/lines_inst__74]
set_property LOC SLICE_X48Y3 [get_cells antenna_top/MONOPOLE/lines_inst__76]
set_property LOC SLICE_X42Y4 [get_cells antenna_top/MONOPOLE/lines_inst__61]
set_property LOC SLICE_X42Y7 [get_cells antenna_top/MONOPOLE/lines_inst__24]
set_property LOC SLICE_X47Y7 [get_cells antenna_top/MONOPOLE/lines_inst__12]
set_property LOC SLICE_X43Y6 [get_cells antenna_top/MONOPOLE/lines_inst__22]
set_property LOC SLICE_X47Y7 [get_cells antenna_top/MONOPOLE/lines_inst__11]
set_property LOC SLICE_X46Y5 [get_cells antenna_top/MONOPOLE/lines_inst__8]
set_property LOC SLICE_X43Y3 [get_cells antenna_top/MONOPOLE/lines_inst__67]
set_property LOC SLICE_X46Y4 [get_cells antenna_top/MONOPOLE/lines_inst__90]
set_property LOC SLICE_X46Y3 [get_cells antenna_top/MONOPOLE/lines_inst__80]
set_property LOC SLICE_X48Y4 [get_cells antenna_top/MONOPOLE/lines_inst__87]
set_property LOC SLICE_X42Y3 [get_cells antenna_top/MONOPOLE/lines_inst__57]
set_property LOC SLICE_X46Y3 [get_cells antenna_top/MONOPOLE/lines_inst__82]
set_property LOC SLICE_X47Y5 [get_cells antenna_top/MONOPOLE/lines_inst__5]
set_property LOC SLICE_X42Y7 [get_cells antenna_top/MONOPOLE/lines_inst__26]
set_property LOC SLICE_X44Y5 [get_cells antenna_top/MONOPOLE/lines_inst__51]
set_property LOC SLICE_X48Y4 [get_cells antenna_top/MONOPOLE/lines_inst__84]
set_property LOC SLICE_X46Y7 [get_cells antenna_top/MONOPOLE/stem_end_inferred_i_11]
set_property LOC SLICE_X46Y5 [get_cells antenna_top/MONOPOLE/lines_inst__9]
set_property LOC SLICE_X46Y4 [get_cells antenna_top/MONOPOLE/lines_inst__94]
set_property LOC SLICE_X45Y5 [get_cells antenna_top/MONOPOLE/lines_inst__95]
set_property LOC SLICE_X48Y3 [get_cells antenna_top/MONOPOLE/lines_inst__75]
set_property LOC SLICE_X44Y6 [get_cells antenna_top/MONOPOLE/lines_inst__32]
set_property LOC SLICE_X46Y5 [get_cells antenna_top/MONOPOLE/lines_inst__59]
set_property LOC SLICE_X42Y7 [get_cells antenna_top/MONOPOLE/lines_inst__28]
set_property LOC SLICE_X46Y6 [get_cells antenna_top/MONOPOLE/lines_inst__39]
set_property LOC SLICE_X42Y7 [get_cells antenna_top/MONOPOLE/lines_inst__29]
set_property LOC SLICE_X46Y7 [get_cells antenna_top/MONOPOLE/lines_inst__37]
set_property LOC SLICE_X42Y3 [get_cells antenna_top/MONOPOLE/lines_inst__58]
set_property LOC SLICE_X43Y3 [get_cells antenna_top/MONOPOLE/lines_inst__69]
set_property LOC SLICE_X46Y7 [get_cells antenna_top/MONOPOLE/lines_inst__35]
set_property LOC SLICE_X42Y3 [get_cells antenna_top/MONOPOLE/lines_inst__56]
set_property LOC SLICE_X42Y6 [get_cells antenna_top/MONOPOLE/lines_inst__41]
set_property LOC SLICE_X44Y5 [get_cells antenna_top/MONOPOLE/lines_inst__52]
set_property LOC SLICE_X42Y4 [get_cells antenna_top/MONOPOLE/lines_inst__63]
set_property LOC SLICE_X46Y7 [get_cells antenna_top/MONOPOLE/lines_inst__38]
set_property LOC SLICE_X42Y6 [get_cells antenna_top/MONOPOLE/lines_inst__40]
set_property LOC SLICE_X44Y5 [get_cells antenna_top/MONOPOLE/lines_inst__48]
set_property LOC SLICE_X42Y6 [get_cells antenna_top/MONOPOLE/lines_inst__44]
set_property LOC SLICE_X46Y5 [get_cells antenna_top/MONOPOLE/lines_inst__0]
set_property LOC SLICE_X47Y7 [get_cells antenna_top/MONOPOLE/lines_inst__16]
set_property LOC SLICE_X46Y6 [get_cells antenna_top/MONOPOLE/lines_inst__2]
set_property LOC SLICE_X46Y5 [get_cells antenna_top/MONOPOLE/lines_inst]
set_property LOC SLICE_X47Y5 [get_cells antenna_top/MONOPOLE/lines_inst__1]
set_property BEL A6LUT [get_cells antenna_top/MONOPOLE/stem_end_inferred_i_1]
set_property LOC SLICE_X46Y197 [get_cells antenna_top/MONOPOLE/stem_end_inferred_i_1]
set_property BEL A6LUT [get_cells antenna_top/MONOPOLE/stem_end_inferred_i_2]
set_property LOC SLICE_X46Y199 [get_cells antenna_top/MONOPOLE/stem_end_inferred_i_2]
set_property BEL A6LUT [get_cells antenna_top/MONOPOLE/stem_end_inferred_i_3]
set_property LOC SLICE_X45Y196 [get_cells antenna_top/MONOPOLE/stem_end_inferred_i_3]
set_property BEL A6LUT [get_cells antenna_top/MONOPOLE/stem_end_inferred_i_4]
set_property LOC SLICE_X46Y198 [get_cells antenna_top/MONOPOLE/stem_end_inferred_i_4]
set_property BEL A6LUT [get_cells antenna_top/MONOPOLE/stem_end_inferred_i_5]
set_property LOC SLICE_X47Y197 [get_cells antenna_top/MONOPOLE/stem_end_inferred_i_5]
set_property BEL D6LUT [get_cells antenna_top/MONOPOLE/stem_end_inferred_i_6]
set_property LOC SLICE_X49Y197 [get_cells antenna_top/MONOPOLE/stem_end_inferred_i_6]
set_property BEL B6LUT [get_cells antenna_top/MONOPOLE/stem_end_inferred_i_7]
set_property LOC SLICE_X46Y199 [get_cells antenna_top/MONOPOLE/stem_end_inferred_i_7]
set_property BEL D6LUT [get_cells antenna_top/MONOPOLE/stem_end_inferred_i_9]
set_property LOC SLICE_X45Y199 [get_cells antenna_top/MONOPOLE/stem_end_inferred_i_9]
set_property BEL A6LUT [get_cells antenna_top/MONOPOLE/stem_end_inferred_i_12]
set_property LOC SLICE_X43Y199 [get_cells antenna_top/MONOPOLE/stem_end_inferred_i_12]
set_property BEL D6LUT [get_cells antenna_top/MONOPOLE/stem_end_inferred_i_13]
set_property LOC SLICE_X43Y196 [get_cells antenna_top/MONOPOLE/stem_end_inferred_i_13]
set_property BEL D6LUT [get_cells antenna_top/MONOPOLE/stem_end_inferred_i_14]
set_property LOC SLICE_X45Y198 [get_cells antenna_top/MONOPOLE/stem_end_inferred_i_14]
set_property BEL C6LUT [get_cells antenna_top/MONOPOLE/stem_end_inferred_i_15]
set_property LOC SLICE_X44Y196 [get_cells antenna_top/MONOPOLE/stem_end_inferred_i_15]
set_property BEL A6LUT [get_cells antenna_top/MONOPOLE/stem_end_inferred_i_16]
set_property LOC SLICE_X43Y197 [get_cells antenna_top/MONOPOLE/stem_end_inferred_i_16]
set_property BEL D6LUT [get_cells antenna_top/MONOPOLE/stem_end_inferred_i_17]
set_property LOC SLICE_X49Y196 [get_cells antenna_top/MONOPOLE/stem_end_inferred_i_17]
set_property BEL D6LUT [get_cells antenna_top/MONOPOLE/stem_end_inferred_i_18]
set_property LOC SLICE_X47Y196 [get_cells antenna_top/MONOPOLE/stem_end_inferred_i_18]
set_property BEL A6LUT [get_cells antenna_top/MONOPOLE/stem_end_inferred_i_19]
set_property LOC SLICE_X47Y198 [get_cells antenna_top/MONOPOLE/stem_end_inferred_i_19]
set_property BEL D6LUT [get_cells antenna_top/MONOPOLE/stem_end_inferred_i_20]
set_property LOC SLICE_X48Y198 [get_cells antenna_top/MONOPOLE/stem_end_inferred_i_20]
